FROM python:latest

RUN pip3 install biopython 
RUN apt install curl unzip
#RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
#RUN unzip -f awscliv2.zip
#RUN  ./aws/install


RUN pip3 install pandas

#CMD ["/bin/bash"]

